#!/bin/bash

## Requires pandoc and a copy of changes.css (if your input text is markdown and you  
##    want red/green coloring of output) 

oldfile=$1
newfile=$2

repodir=$(git rev-parse --show-toplevel)

context_lines=65535 # Set to be very large to include whole document as output.

git diff -U${context_lines}  --no-index --word-diff -- ${oldfile} ${newfile} |\
   tail +6  |\
   sed 's/\[-/~~/g;s/-]/~~/g;' |\
   sed 's/{\+/__/g;s/+}/__/g' |\
   pandoc -s -H changes.css -f markdown -t html 


